
###
GET http://localhost:9090/user/getprofile/62551877db872a779a0491dc

###
POST http://localhost:9090/user/register HTTP/1.1
content-type: application/json

{
    "fullName":"Pawan Shah",
    "email": "pawan09@gmail.com",
    "password": "pawan09"
}

###
POST http://localhost:9090/user/login/ HTTP/1.1
content-type: application/json

{
    "email": "ravisharcs09@gmail.com",
    "password": "ravics09"
}

###
GET HTTP://localhost:9090/user

###
GET HTTP://localhost:9090/user/profile/624540ca4ac88651a691f99e HTTP/1.1
content-type: application/json
# Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhdmlzaGFybWFjczA5QGdtYWlsLmNvbSIsImlhdCI6MTY0ODc0MTEzMywiZXhwIjoxNjQ4ODI3NTMzfQ.9w9mGSALjMRxIS014hh0lugorOMq7qjH1rBUxxQOrpo


