export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";

export const SET_THEME = "SET_THEME";
export const DEFAULT_THEME = "DEFAULT_THEME";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";